name: status-checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Test changed source files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: examples/**
      - name: validate coding style and functionality
        if: ${{ steps.changed-files.outputs.any_changed == 'true' ||
                github.event_name == 'workflow_dispatch' }}
        run: |
            sudo apt-get install -q -y clang-format-12
            sudo apt-get install -q -y cppcheck
            sudo apt-get install -q -y gcc-11
            .ci/check-newline.sh
            .ci/check-format.sh
            .ci/static-analysis.sh
            .ci/build-n-run.sh
        shell: bash
